apiVersion: v1
kind: Service
metadata:
  name: camera-service
  namespace: assignment
spec:
  selector:
    app: camera
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
