apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-deployment
  namespace: assignment
  labels:
    app: camera
spec:
  replicas: 2
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
    spec:
      containers:
        - name: camera
          image: ccuni/camera-service-2025w
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
