apiVersion: v1
kind: Service
metadata:
  name: face-recognition
  namespace: assignment
spec:
  selector:
    app: face-recognition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
