apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-recognition-deployment
  namespace: assignment
  labels:
    app: face-recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-recognition
  template:
    metadata:
      labels:
        app: face-recognition
    spec:
      containers:
        - name: face-recognition
          image: ccuni/face-recognition-service-2025w
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
