apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-analysis-deployment
  namespace: assignment
  labels:
    app: image-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-analysis
  template:
    metadata:
      labels:
        app: image-analysis
    spec:
      containers:
        - name: image-analysis
          image: ccuni/image-analysis-service-2025w
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
